config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     'user_login'   => 'usersessions#new'
  post    'user_login'   => 'usersessions#create'
  delete  'user_logout'  => 'usersessions#destroy'

  namespace :api, defaults: {format: :json} do
    post 'signup' => 'users#create'
    post 'login' => 'sessions#create'
    post 'send_code' => 'users#send_code'
    post 'user_modify' => 'users#modify'
    resources :users do
      patch :reset_password, on: :collection
      get :center, on: :collection
      get :verify_bank, on: :collection
    end
    resources :products do
      get :recommend_list, on: :collection
    end
    resources :records do
      post :notify, on: :collection
      get :search, on: :collection
      get :period_bonus, on: :collection
      get :subordinates_bonus, on: :collection
    end
    resources :carousels
  end

  resources :users do
    get :export, on: :collection
  end

  resources :products do
    get :confirm, on: :member
    get :deny, on: :member
    get :disable, on: :member
  end

  resources :records do
    get :confirm, on: :member
    get :deny, on: :member
  end

  resources :carousels

  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  RECORD_STATUS = ["待审核", "已审核"]

  belongs_to :user
  belongs_to :product

  state_machine :status, :initial => :'待审核' do
    event :confirm do
      transition :'待审核' => :'已审核'
    end
    event :deny do
      transition :'已审核' => :'待审核'
    end
  end
end

app/controllers/api/records_controller.rb
class Api::RecordsController < Api::BaseController
  skip_before_action :authenticate_user!, only: [:notify]

  def index
    @records = current_user.records
  end

  def search
    connection = ActiveRecord::Base.connection
    sql = "select id, product_id, total_prize, total_insured, policy_no, start_date, end_date, sell_date, bonus, commis from records where user_id = #{current_user.id} "
    c1 = ""
    c2 = ""
    c1 =  " AND product_id in (select id from products where name like '%#{params[:product_name]}%') " if params[:product_name]
    c2 =  " AND policy_no like '%#{params[:policy_no]}%' " if params[:policy_no]
    @records = connection.execute(sql + c1 + c2)
  end

  def period_bonus
    @records = current_user.records.where("sell_date between ? AND ?", params[:start_date], params[:end_date])
  end

  def subordinates_bonus
    @subordinates = current_user.subordinates
  end

  def notify
    # Rails.logger.warn "notify #{Time.now}, sign: #{params[:sign]}, other #{params};"
    # params = {"sign"=>"k5h1TtKzE/he3u2OM3bqI8ZHueW0hYLOT3VjvjcR4bZMmVy+4B6UcvO+uaZxbwTbJ9ui30vMuvPMLePY2036RJEbTnIvETlIE0w0YDs7mRj8XaZSnzvfUvhHU8baPvs1URrPcKENsYmflCcsdPG/J6jsA7Yp/dcAqROkg96+GQ0=", "timestamp"=>"20161012034610010", "bizContent"=>"PXcdop/YlCrNX8ePQss0+XvFPk5z/ToxDBS96rHx+pEozbe2jDqQgnGPDIyHPNenWFlwbMPM8ZFgZfgqf5TRDFYOhxKJGmbre/RJ8el/Np3EGpHpI3NUYSwuYuW78cDLd7JWRHbeEB4AjGytICx2YGYy/fl3XADaerObEXpNQloJodBanbaBGr8XgKRh7HdVjUAVUIxL0pq2ZrM5XMZUIW0AAWJpKiV9JHE0p3zcgKQnYr+HmemidDbnQOKFQMaiVOh+/puSe+9xR05gSiMY4vWQaj+HeWbRXfmgge/IrevaqcDIPnhmLIgQsMgXI0oFdg3uLswIm7LUZwL3DVsSnpq6UzIUgxJTn0FvDdsB7TsGJ0Mx/ftlYBXxFF1UOTuwGTLyc8b6kqFlJRrdVLN75BVguIKg4TzR2wsQq/8qsPKcJ2/H2vGwef9EI37NO3l0pNXt7yTfA5eanE5aP8x90cKQJb1zET5EcQkkoPeuGu10XePuvW9E/C/iqOZMdoaJ", "signType"=>"RSA", "charset"=>"UTF-8", "format"=>:json, "serviceName"=>"promotePolicyNotify", "controller"=>"api/records", "action"=>"notify"}
    params_hash = params
    params_hash.delete("sign")
    params_hash.delete("action")
    params_hash.delete("controller")
    params_hash.delete("serviceName")
    # json = params.sort.to_h.to_json

    appKey = ENV['zhongan_appKey']

    # Load PUBLIC key
    private_key = OpenSSL::PKey::RSA.new(File.read(ENV['zhongan_private_key']))

    # We have received the following data
    message = params_hash["bizContent"]
    decrypt_message = decrypt_msg(private_key, message) rescue api_error(status: 401)

    json = JSON.parse decrypt_message

    s = json["bizContent"]
    d = [s].pack("H*")

    key = ENV['zhongan_key']
    dec = RC4.new(key)
    decrypted = dec.decrypt(d) rescue api_error(status: 401)

    contents = JSON.parse decrypted

    # Verify the message & its signature
    # if public_key.verify(OpenSSL::Digest::SHA256.new, signature, message)
    #     "VALID: Signed by pair private key"
    # else
    #     "NOT VALID: Data tampered or private-public key mismatch!"
    # end
    # Rails.logger.warn "notify finished #{Time.now}, json: #{json};"
    Rails.logger.warn "notify finished #{Time.now}, decrypted: #{decrypted};"

    @record = Record.new(user_id: contents["extraInfo"]["user_id"],
                         product_id: contents["extraInfo"]["product_id"],
                         sell_date: Time.now.strftime("%F"),
                         qty: 1,
                         total_prize: json["premium"],
                         total_insured: json["sumInsured"],
                         start_date: json["effectiveDate"],
                         end_date: json["expiryDate"],
                         policy_no: json["policyNo"])
    @product = Product.find(contents["extraInfo"]["product_id"].to_i)
    @record.bonus = @product.bonus
    @record.commis = @product.ratio * json["premium"].to_f
    if @record.save
      @record.confirm
      if @record.user.status == "未激活"
        @record.user.activate
        @record.user.superior.newbonus.create!(subordinate_id: @record.user.id, bonus: 100) if @record.user.superior
      end
      render plain: "success"
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < BaseController
  before_action :logged_in?
  def index
    if current_user.nil?
      @records = Record.all
    else
      @records = Record.where('user_id in (?)', current_user.subordinates.map {|u| u.id})
    end
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    if @record.save
      redirect_to records_url
    else
      render 'new'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to records_url
    else
      render 'edit'
    end
  end

  def destroy
    Record.find(params[:id]).destroy
    redirect_to records_url
  end

  def confirm
    Record.find(params[:id]).confirm
    redirect_to records_url
  end

  def deny
    Record.find(params[:id]).deny
    redirect_to records_url
  end

  private
    def record_params
      params.require(:record).permit(:user_id, :product_id, :sell_date, :qty, :total_prize,
                                     :customer_name, :customer_cell, :status)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
       <h4 class="panel-title text-center"><%=Record.model_name.human%></h4>
    </div>
  <%= simple_form_for(@record) do |f| %>
  <div class="panel-body">
    <%= f.input :product_id, collection: Product.all, :include_blank => false %>
    <%= f.input :sell_date %>
    <%= f.input :customer_name %>
    <%= f.input :customer_cell %>
    <%= f.input :qty %>
    <%= f.input :total_prize %>
  </div>
  <div class="panel-footer text-center">
    <%= f.button :submit, class: "btn btn-danger" %>
    <%= link_to t(:back), :back, class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/records/_record.html.erb
<tr>
  <td><%= record.id %></td>
  <td><%= User.find(record.user_id).cell %></td>
  <td><%= record.user.superior.name if record.user.superior %></td>
  <td><%= Product.find(record.product_id).name if record.product %></td>
  <td><%= record.sell_date %></td>
  <td><%= record.customer_name %></td>
  <td><%= record.customer_cell %></td>
  <td><%= record.qty %></td>
  <td><%= record.total_prize %></td>
  <td><%= record.status %></td>
  <td><%= link_to t(:destroy), record_path(record), method: :delete, data: {confirm: t(:are_you_sure)} %></td>
  <td><%= link_to t(:confirm), confirm_record_path(record) if current_user.nil? %></td>
  <td><%= link_to t(:deny), deny_record_path(record) if current_user.nil? %></td>
</tr>

app/views/records/index.html.erb
<div class="col-md-12">
  <h3><%= t(:record_list) %></h3>
</div>
<div class="col-md-12">
  <table class="table">
    <thead>
      <tr>
        <th><%= Record.human_attribute_name(:id) %></th>
        <th><%= Record.human_attribute_name(:user_id) %></th>
        <th><%= Record.human_attribute_name(:superior) %></th>
        <th><%= Record.human_attribute_name(:product_id) %></th>
        <th><%= Record.human_attribute_name(:sell_date) %></th>
        <th><%= Record.human_attribute_name(:customer_name) %></th>
        <th><%= Record.human_attribute_name(:customer_cell) %></th>
        <th><%= Record.human_attribute_name(:qty) %></th>
        <th><%= Record.human_attribute_name(:total_prize) %></th>
        <th><%= Record.human_attribute_name(:status) %></th>
        <th colspan="3"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @records %>
    </tbody>
  </table>
</div>