config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     'user_login'   => 'usersessions#new'
  post    'user_login'   => 'usersessions#create'
  delete  'user_logout'  => 'usersessions#destroy'

  namespace :api, defaults: {format: :json} do
    post 'signup' => 'users#create'
    post 'login' => 'sessions#create'
    post 'send_code' => 'users#send_code'
    post 'user_modify' => 'users#modify'
    resources :users do
      patch :reset_password, on: :collection
      get :center, on: :collection
      get :verify_bank, on: :collection
    end
    resources :products do
      get :recommend_list, on: :collection
    end
    resources :records do
      post :notify, on: :collection
      get :search, on: :collection
      get :period_bonus, on: :collection
      get :subordinates_bonus, on: :collection
    end
    resources :carousels
  end

  resources :users do
    get :export, on: :collection
  end

  resources :products do
    get :confirm, on: :member
    get :deny, on: :member
    get :disable, on: :member
  end

  resources :records do
    get :confirm, on: :member
    get :deny, on: :member
  end

  resources :carousels

  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
  end

end

app/views/admin/admins/_admin.html.erb
<tr>
  <td><%= admin.id %></td>
  <td><%= admin.name %></td>
  <td><%= I18n.l(admin.created_at) %></td>
  <td><%= I18n.l(admin.updated_at) %></td>
  <td><%= link_to t(:edit), edit_admin_admin_path(admin) %></td>
</tr>

app/views/admin/admins/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
       <h4 class="panel-title text-center"><%=Admin.model_name.human%></h4>
    </div>
  <%= simple_form_for([:admin, @admin]) do |f| %>
    <div class="panel-body">
      <%= f.input :name %>
      <%= f.input :password %>
      <%= f.input :password_confirmation %>
    </div>
    <div class="panel-footer text-center">
      <%= f.button :submit, class: "btn btn-danger" %>
      <%= link_to t(:back), :back, class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/admin/admins/edit.html.erb
<%= render 'form' %>

app/views/admin/admins/index.html.erb
<div class="col-md-10">
  <h3><%= t(:admin_list) %></h3>
</div>
<div class="col-md-2">
  <%= link_to t(:new_admin), new_admin_admin_path, class: "btn btn-danger" %>
</div>
<div class="col-md-12">
  <table class="table">
    <thead>
      <tr>
        <th><%= Admin.human_attribute_name(:id) %></th>
        <th><%= Admin.human_attribute_name(:name) %></th>
        <th><%= Admin.human_attribute_name(:created_at) %></th>
        <th><%= Admin.human_attribute_name(:updated_at) %></th>
        <th colspan="2"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @admins %>
    </tbody>
  </table>
</div>

app/views/admin/admins/new.html.erb
<%= render 'form' %>