config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     'user_login'   => 'usersessions#new'
  post    'user_login'   => 'usersessions#create'
  delete  'user_logout'  => 'usersessions#destroy'

  namespace :api, defaults: {format: :json} do
    post 'signup' => 'users#create'
    post 'login' => 'sessions#create'
    post 'send_code' => 'users#send_code'
    post 'user_modify' => 'users#modify'
    resources :users do
      patch :reset_password, on: :collection
      get :center, on: :collection
      get :verify_bank, on: :collection
    end
    resources :products do
      get :recommend_list, on: :collection
    end
    resources :records do
      post :notify, on: :collection
      get :search, on: :collection
      get :period_bonus, on: :collection
      get :subordinates_bonus, on: :collection
    end
    resources :carousels
  end

  resources :users do
    get :export, on: :collection
  end

  resources :products do
    get :confirm, on: :member
    get :deny, on: :member
    get :disable, on: :member
  end

  resources :records do
    get :confirm, on: :member
    get :deny, on: :member
  end

  resources :carousels

  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
  end

end

app/models/product.rb
require 'rc4'

class Product < ActiveRecord::Base
  PRODUCT_STATUS = ["待审核", "已审核"]
  PRODUCT_ALL_STATUS = ["已审核", "作废"]
  PRODUCT_ALL_TYPES = ["医疗", "意外", "航旅"]

  belongs_to :user
  has_many :records, dependent: :destroy

  mount_uploader :image, QrcodeUploader

  state_machine :status, :initial => :'待审核' do
    event :disable do
      transition [:'待审核', :'已审核'] => :'作废'
    end
    event :confirm do
      transition :'待审核' => :'已审核'
    end
    event :deny do
      transition :'已审核' => :'待审核'
    end
  end

  def promoturl(user)
    payChannel           = "wxpay"
    returnUrl            = ENV['return_url']
    json                 = ""
    json                 = "{\"extraInfo\":{\"user_id\":#{user.id}, \"product_id\":#{self.id}}}" if user
    # json                 = {extraInfo:{user_id: user.id}}
    # json                 = JSON::generate(data)

    key = ENV['zhongan_key']
    enc = RC4.new(key)
    encrypted = enc.encrypt(json)
    bizContent = encrypted.unpack('H*')[0]

    self.url + "&" + "payChannel=" + payChannel + "&" + "returnUrl=" + returnUrl + "&" + "bizContent=" + bizContent
  end

  # def Product.notify(user, bank_code, card_no)
  #
  #     key = "open20160501"
  #     enc = RC4.new(key)
  #     encrypted = enc.encrypt(data)
  #
  #     sign_str = "bank_code=" + bank_code + "&" +
  #                "card_no=" + card_no + "&" +
  #                "card_type=" + card_type + "&" +
  #                "input_charset=" + input_charset + "&" +
  #                "interface_version=" + interface_version + "&" +
  #                "merchant_code=" + merchant_code + "&" +
  #                "mobile=" + mobile + "&" +
  #                "service_type=" + service_type
  #
  #     # pri = OpenSSL::PKey::RSA.new File.read '/Users/hielf/workspace/keys/key.pem'
  #     pri = OpenSSL::PKey::RSA.new File.read '/var/keys/key.pem'
  #     sign = pri.sign('md5', sign_str.force_encoding("utf-8"))
  #     signature = Base64.encode64(sign)
  #     signature = signature.delete("\n").delete("\r")
  #
  #     uri = URI.parse("https://api.dinpay.com/gateway/api/express")
  #     res = Net::HTTP.post_form(uri, service_type: service_type, merchant_code: merchant_code,
  #           interface_version: interface_version, input_charset: input_charset,
  #           sign_type: sign_type, sign: URI::encode(signature), mobile: mobile, bank_code: bank_code,
  #           card_type: card_type, card_no: card_no)
  #
  #     result = Nokogiri::XML(res.body)
  #     return ((status == "success") ? true : false)
  #   end

end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::BaseController
  # skip_before_action :authenticate_user!, only: [:index, :send_code]
  def index
    if current_user.user_type == "normal"
      @products = Product.where(status: "已审核", user_id: nil)
    else
      superior = current_user.superior
      @products = superior.products.where(status: "已审核") if superior
    end
    @current_user = current_user
  end

  def show
    @product = Product.find(params[:id])
    @current_user = current_user
  end

  def recommend_list
    if current_user.user_type == "normal"
      @products = Product.where(status: "已审核", user_id: nil, recommend: true)
    else
      superior = current_user.superior
      @products = superior.products.where(status: "已审核", recommend: true) if superior
    end

    @current_user = current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < BaseController
  # before_action :logged_in?
  def index
    if current_user
      @products = current_user.products
    else
      @products = Product.all
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_url
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_url
  end

  def confirm
    Product.find(params[:id]).confirm
    redirect_to products_url
  end

  def deny
    Product.find(params[:id]).deny
    redirect_to products_url
  end

  def disable
    Product.find(params[:id]).disable
    redirect_to products_url
  end

  private
    def product_params
      params.require(:product).permit(:name, :prize, :image, :desc, :url, :status, :ratio,
                              :bonus, :recommend, :user_id, :product_type)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
       <h4 class="panel-title text-center"><%=Product.model_name.human%></h4>
    </div>
  <%= simple_form_for(@product) do |f| %>
  <div class="panel-body">
    <%= f.input :product_type, collection: Product::PRODUCT_ALL_TYPES, :include_blank => false %>
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :prize %>
    <%= f.input :ratio %>
    <%= f.input :bonus %>
    <%= f.input :desc %>
    <%= f.input :url %>
    <%= f.input :recommend %>
    <%= f.input :user_id, collection: User.where(user_type: "channel", superior_id: nil), :include_blank => true %>
    <%= f.input :status, collection: Product::PRODUCT_STATUS, :include_blank => false %>
  </div>
  <div class="panel-footer text-center">
    <%= f.button :submit, class: "btn btn-danger" %>
    <%= link_to t(:back), :back, class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.product_type %></td>
  <td><%= product.name %></td>
  <td><%= product.desc %></td>
  <td><%= link_to "图片", product.image.url %></td>
  <td><%= link_to "产品链接", product.url %></td>
  <td><%= link_to "推广链接", product.promoturl(User.last) %></td>
  <td><%= product.user.name if product.user %></td>
  <td><%= product.status %></td>
  <td><%= link_to t(:edit), edit_product_path(product) %></td>
  <td><%= link_to t(:confirm), confirm_product_path(product) %></td>
  <td><%= link_to t(:disable), disable_product_path(product) %></td>
  <td><%= link_to t(:destroy), product_path(product), method: :delete, data: {confirm: t(:are_you_sure)} %></td>
</tr>

app/views/products/index.html.erb
<div class="col-md-10">
  <h3><%= t(:product_list) %></h3>
</div>
<div class="col-md-2">
  <%= link_to t(:new_product), new_product_path, class: "btn btn-danger" if current_user.nil? %>
</div>
<div class="col-md-12">
  <table class="table">
    <thead>
      <tr>
        <th><%= Product.human_attribute_name(:id) %></th>
        <th><%= Product.human_attribute_name(:product_type) %></th>
        <th><%= Product.human_attribute_name(:name) %></th>
        <th><%= Product.human_attribute_name(:desc) %></th>
        <th><%= Product.human_attribute_name(:image) %></th>
        <th><%= Product.human_attribute_name(:url) %></th>
        <th><%= Product.human_attribute_name(:promoturl) %></th>
        <th><%= Product.human_attribute_name(:user_id) %></th>
        <th><%= Product.human_attribute_name(:status) %></th>
        <th colspan="4"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @products %>
    </tbody>
  </table>
</div>