config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     'user_login'   => 'usersessions#new'
  post    'user_login'   => 'usersessions#create'
  delete  'user_logout'  => 'usersessions#destroy'

  namespace :api, defaults: {format: :json} do
    post 'signup' => 'users#create'
    post 'login' => 'sessions#create'
    post 'send_code' => 'users#send_code'
    post 'user_modify' => 'users#modify'
    resources :users do
      patch :reset_password, on: :collection
      get :center, on: :collection
      get :verify_bank, on: :collection
    end
    resources :products do
      get :recommend_list, on: :collection
    end
    resources :records do
      post :notify, on: :collection
      get :search, on: :collection
      get :period_bonus, on: :collection
      get :subordinates_bonus, on: :collection
    end
    resources :carousels
  end

  resources :users do
    get :export, on: :collection
  end

  resources :products do
    get :confirm, on: :member
    get :deny, on: :member
    get :disable, on: :member
  end

  resources :records do
    get :confirm, on: :member
    get :deny, on: :member
  end

  resources :carousels

  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
  end

end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:title), '#', class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if admin_logged_in? %>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to User.model_name.human, users_path %></li>
          <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to Product.model_name.human, products_path %></li>
          <li class="<%= 'active' if params[:controller] == 'records' %>"><%= link_to Record.model_name.human, records_path %></li>
          <li class="<%= 'active' if params[:controller] == 'carousels' %>"><%= link_to Carousel.model_name.human, carousels_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if params[:controller] == 'admin/admins' %>"><%= link_to Admin.model_name.human, admin_admins_path %></li>
          <li><%= link_to t('logout'), admin_logout_path, method: :delete %></li>
        </ul>
      <% elsif user_logged_in? %>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to User.model_name.human, users_path %></li>
          <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to Product.model_name.human, products_path %></li>
          <li class="<%= 'active' if params[:controller] == 'records' %>"><%= link_to Record.model_name.human, records_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('logout'), user_logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('admin_login'), admin_login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title><%= t(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/admin_header' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>
  

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>链金士</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/admin_header' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>


</body>
</html>